### ISSUE TITLE
Module order changes when specifying per page position

### ISSUE THREAD

**Issue by lawrence-jeff** [shbatm/MMM-Carousel#29]
Is it expected that you would get different ordering between the two scenarios below

- Adding a module to a slide with no position (so position defined at the module level) in this case top_center
   `slides: 
          [ [  {name:'clock', carouselId: "1"},
               'MMM-CalendarExt2',
               'currentweather',
               'weatherforecast',
               'MMM-Todoist',
               'MMM-homeassistant-sensors',
               'MMM-StopwatchTimer',
               'calendar', ],`
- Adding a module to a slide and specifying the same position as the module 'top_center'
 `slides: 
          [ [  {name:'clock',position:"top_center", carouselId: "1"},
               'MMM-CalendarExt2',
               'currentweather',
               'weatherforecast',
               'MMM-Todoist',
               'MMM-homeassistant-sensors',
               'MMM-StopwatchTimer',
               'calendar', ],`

In the first case - the clock is above calendar (which also uses top_center), in the second case it is below.

I wouldn't expect these to vary.. but they do consistently.  Also if I add clock to the ignore modules it positions correctly as the first top_center module. I'm trying to keep the clock at the top in the first slide and move it in the second.. but no combination of reordering positions seems to do that if I have a position specified in the slide configuration.

**Comment by shbatm** [comment]
If you use the Carousel module config to 'move' a module, it will redraw it in the new position *after* showing the existing modules in that position in the order they are configured. In the 2nd example above, you could "move" the calendar as well (e.g. add a position to `calendar` as well; another alternative is to specify a 2nd clock module with a different Carousel ID in the new position. Clock is a small enough module that it won't have any impacts to specify it twice (that case was the original case for adding a `carouselId` parameter.

Closing this due to age and mechanism by which the modules are moved.
